# Generated by Django 4.2.5 on 2023-09-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=255)),
                ('projectDesc', models.CharField(max_length=555)),
                ('projectGitHub', models.URLField(max_length=555)),
                ('projectDeployed', models.URLField(max_length=555)),
            ],
        ),
    ]
