# Generated by Django 4.2.5 on 2023-09-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_projectpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectPic',
            field=models.ImageField(upload_to='projectPics/'),
        ),
    ]
