# Generated by Django 4.2.5 on 2023-09-16 08:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_projectpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogName', models.CharField(max_length=255)),
                ('blogDesc', ckeditor.fields.RichTextField()),
                ('blogDate', models.DateField(auto_now_add=True)),
                ('blogPic', models.ImageField(upload_to='blogPics/')),
                ('blogCategory', models.CharField(max_length=255)),
            ],
        ),
    ]
