# Generated by Django 4.2.5 on 2023-09-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blog_blogauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogCategory', models.CharField(max_length=255)),
            ],
        ),
    ]
