# Generated by Django 4.2.5 on 2023-09-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogCategory',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogTag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.blogcategory'),
        ),
    ]
